const prompts = [
  ' My favorite way to spend the day is…',
  'If I could talk to my teenage self, the one thing I would say is…',
  'The two moments I’ll never forget in my life are… Describe them in great detail, and what makes them so unforgettable.',
  'Make a list of 30 things that make you smile.',
  'The words I’d like to live by are…',
  'I couldn’t imagine living without…',
  'When I’m in pain — physical or emotional — the kindest thing I can do for myself is…',
  'What does unconditional love look like for you?',
  'What would you do if you loved yourself unconditionally? How can you act on these things whether you do or don’t?',
  'I really wish others knew this about me…',
  'Name what is enough for you.',
  'If my body could talk, it would say…',
  'Name a compassionate way you’ve supported a friend recently. Then write down how you can do the same for yourself.',
  'What do you love about life?',
  'What always brings tears to your eyes?',
  'Write about your first love — whether a person, place or thing.',
  'Using 10 words, describe yourself.',
  'What’s surprised you the most about your life or life in general?',
  'What can you learn from your biggest mistakes?',
  'I feel most energized when…',
  'Write a list of questions to which you urgently need answers.',
  'What’s one topic you need to learn more about to help you live a more fulfilling life? (Then learn about it.)',
  'I feel happiest in my skin when…',
  'Make a list of everything you’d like to say no to.',
  'Make a list of everything you’d like to say yes to.',
  'Write the words you need to hear.',
  'Describe your perfect day.',
  'Discuss 5 things you wish others knew about you.',
  'Write one paragraph about what made you happy today.',
  'Identify three short term goals and one long term goal.',
  'What is a self-care strategy you have always been curious in trying?',
  'What inspires you?',
  'Make a list of 15 things that make you happy.',
  'What are your best character traits?',

  'Describe a situation in which you helped someone else. How do you think it made them feel? How did it make you feel?',
  'What advice would you give to someone going through a hard time?',
  'Describe a hardship you have had. How does it make you feel reflecting back on it? What do you feel you learned?',
  'What makes you feel fulfilled? ',
  'What things are you avoiding dealing with?',
  'What do you need right now?',
  'Write down 5 things that make you incredibly happy and describe why they make you feel this way.',
  'What do you fear the most? Why? Is your fear rational?',

  'Write about your one of your happiest memories?',
  'Write about the people in your life that make you feel the most “at ease” and what they do to make you feel that way.',
  'Write about the last time you cried. What caused you to cry?',
  'Write about the last time you laughed really hard. What was so funny?',
  'Write a letter to the future YOU.',
  'What has your anxiety taught you about yourself?',

  'In detail, describe a perfect day.',

  'Write a letter to a person who has positively impacted you'

];
export default prompts;
