const prompts = [
  ' My favorite way to spend the day is…',
  'If I could talk to my teenage self, the one thing I would say is…',
  'The two moments I’ll never forget in my life are… Describe them in great detail, and what makes them so unforgettable.',
  'Make a list of 30 things that make you smile.',
  'The words I’d like to live by are…',
  'I couldn’t imagine living without…',
  'When I’m in pain — physical or emotional — the kindest thing I can do for myself is…',
  'Make a list of the people in your life who genuinely support you, and who you can genuinely trust. (Then make time to hang out with them.)',
  'What does unconditional love look like for you?',
  'What would you do if you loved yourself unconditionally? How can you act on these things whether you do or don’t?',
  'I really wish others knew this about me…',
  'Name what is enough for you.',
  'If my body could talk, it would say…',
  'Name a compassionate way you’ve supported a friend recently. Then write down how you can do the same for yourself.',
  'What do you love about life?',
  'What always brings tears to your eyes?',
  'Write about a time when work felt real to you, necessary and satisfying. Paid or unpaid, professional or domestic, physical or mental.',
  'Write about your first love — whether a person, place or thing.',
  'Using 10 words, describe yourself.',
  'What’s surprised you the most about your life or life in general?',
  'What can you learn from your biggest mistakes?',
  'I feel most energized when…',
  'Write a list of questions to which you urgently need answers.',
  'Make a list of everything that inspires you — from books to websites to quotes to people to paintings to stores to the stars.',
  'What’s one topic you need to learn more about to help you live a more fulfilling life? (Then learn about it.)',
  'I feel happiest in my skin when…',
  'Make a list of everything you’d like to say no to.',
  'Make a list of everything you’d like to say yes to.',
  'Write the words you need to hear.',
  'Describe your perfect day.',
  'Discuss 5 things you wish others knew about you.',
  'Write one paragraph about what made you happy today.',
  'Identify three short term goals and one long term goal.',
  'What is a self-care strategy you have always been curious in trying?',
  'What inspires you?',
  'Make a list of 15 things that make you happy.',
  'Write about an important person in your life who you are grateful for. What do you admire about this person, why have they had such an impact on your life, and what would you like to tell them? ',
  'What are your best character traits?',
  'Write down three to five things that trigger feelings of anxiety in you and identify one to three coping strategies you can attempt to implement in response to these.',
  'Pick one positive word you would like to focus on today and describe what it makes you feel or what you associate with it.',
  'Describe a situation in which you helped someone else. How do you think it made them feel? How did it make you feel?',
  'What self-care strategies have you used in the past? Rate them from 1-10, 10 being the most effective and helpful, 1 being the least. ',
  'What advice would you give to someone going through a hard time?',
  'What is a quote that you want to manifest on for the rest of the week? How can you apply it to your life every day this week?',
  'Describe a hardship you have had. How does it make you feel reflecting back on it? What do you feel you learned?',
  'What makes you feel fulfilled? ',
  'What things are you avoiding dealing with?',
  'What do you need right now?',
  'Write down 5 things that make you incredibly happy and describe why they make you feel this way.',
  'What do you fear the most? Why? Is your fear rational?',
  'In the next year, what are 5 improvements you would like to make regarding your life? Write about the improvements and create a plan to accomplish each one.',
  'Write about your one of your happiest memories?',
  'Write about the people in your life that make you feel the most “at ease” and what they do to make you feel that way.',
  'Write about a difficult memory and the coping mechanisms you used at the time. Would you change the way you dealt? How?',
  'Write about the last time you cried. What caused you to cry?',
  'Write about the last time you laughed really hard. What was so funny?',
  'Write a letter to the future YOU.',
  'What has your anxiety taught you about yourself?',
  'Write down a list of "regrets". Either throw them away or toss them into a fire. (Let go of past regrets & move on).',
  'In detail, describe a perfect day.',
  'Write a letter to a person who has negatively impacted you. (Again, you don’t actually have to send it out).',
  'Write a letter to a person who has positively impacted you'

];
export default prompts;
